<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>

		<RootNamespace>Th11s.ACMEServer.CLI</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ACMEServer.CertProvider.ADCS\ACMEServer.CertProvider.ADCS.csproj" />
		<ProjectReference Include="..\ACMEServer.Storage.FileSystem\ACMEServer.Storage.FileSystem.csproj" />
		<ProjectReference Include="..\ACMEServer\ACMEServer.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.DirectoryServices" Version="10.0.12" />
		<PackageReference Include="System.CommandLine" Version="2.0.12" />
	</ItemGroup>

</Project>
